---
- hosts: all
  become: yes
  tasks:
#### conditons
    - name: install a webserver redhat/centos
      yum:
        name: httpd
        state: latest
      when: ansible_distribution == 'RedHat'
    - name: start the service
      service:
         name: httpd
         state: started
      when: ansible_distribution == 'RedHat'
      
    - name: install a webserver on ubuntu
      apt:
        name: apache2
        state: latest
      when: ansible_distribution == 'Ubuntu' && ansible_distribution_major_version == '18.04'
    - name: start the service
      service:
         name: apache2
         state: started
      when: ansible_distribution == 'Ubuntu'

    - name: install a webserver Amazon
      yum:
        name: httpd
        state: latest
      when: ansible_distribution == 'Amazon'
    - name: start the service
      service:
         name: httpd
         state: started
      when: ansible_distribution == 'Amazon'

=============================================================================================
---
- hosts: test-server
  tasks:
    - name: stop nginx if running 
      service:
          name: nginx
          state: stopped
          
    - name: uninstall nginx if already installed on ubuntu
      apt: 
          name: nginx 
          state: absent
      when: ansible_os_family == "ubuntu" and ansible_distribution_version == "20.04"

    - name: uninstall nginx on redhat/amazon
      apt: 
          name: nginx 
          state: absent
      when: ansible_os_family == "Redhat" || ansible_os_family == "Amazon"
      
    - name: install nginx on ubuntu
      apt: 
          name: nginx 
          state: present
      when: ansible_os_family == "ubuntu" and ansible_distribution_version == "20.04"
      
    - name: install nginx on redhat/amazon
      apt: 
          name: nginx 
          state: present
      when: ansible_os_family == "Redhat" || ansible_os_family == "Amazon"
      
    - name: start nginx service
      service:
          name: nginx
          state: started
